theme: jekyll-theme-slate
gem "github-pages", group: :jekyll_plugins
url: https://www.rapyuta-robotics.com
title: The ALICA Framework
description: A Language for Interactive Cooperative Agents
show_downloads: false
plugins:
  - jekyll-relative-links
  - jekyll-katex
relative_links:
  enabled: true
  collections: true
google_analytics: UA-53174037-1

